'use strict';
const {DatabaseSync}=require('node:sqlite');const fs=require('node:fs');const path=require('node:path');const {randomUUID,createHash}=require('node:crypto');
const {analyze,RULE_VERSION}=require('./business.cjs');
const hash=b=>createHash('sha256').update(b).digest('hex');
const empty=()=>({version:2,revision:1,datasets:{payroll:[],ledger:[],bank:[]},imports:[],evidence:[],reports:[],events:[]});
function must(ok,message,status=400){if(!ok){const e=new Error(message);e.status=status;throw e;}}
class Store{
  constructor(filename){if(filename!==':memory:'){fs.mkdirSync(path.dirname(filename),{recursive:true,mode:0o700});}this.db=new DatabaseSync(filename);this.db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS workspace(id INTEGER PRIMARY KEY, json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS files(id TEXT PRIMARY KEY, body BLOB NOT NULL); CREATE TABLE IF NOT EXISTS previews(id TEXT PRIMARY KEY, json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY, json TEXT NOT NULL);');this.db.prepare('INSERT OR IGNORE INTO workspace VALUES(1,?)').run(JSON.stringify(empty()));if(filename!==':memory:')fs.chmodSync(filename,0o600);}
  read(){return JSON.parse(this.db.prepare('SELECT json FROM workspace WHERE id=1').get().json);}
  mutate(expected,action,fn){this.db.exec('BEGIN IMMEDIATE');try{const s=this.read();if(expected!=null)must(s.revision===expected,'Data changed. Refresh and preview again.',409);const result=fn(s);s.events.push({id:randomUUID(),at:new Date().toISOString(),action,revision:s.revision});this.db.prepare('UPDATE workspace SET json=? WHERE id=1').run(JSON.stringify(s));this.db.exec('COMMIT');return result||s;}catch(e){this.db.exec('ROLLBACK');throw e;}}
  preview(kind,filename,buffer,rows,sheet){const s=this.read(),p={id:randomUUID(),kind,filename,hash:hash(buffer),rows,sheet,revision:s.revision,createdAt:Date.now()};this.db.prepare('DELETE FROM previews WHERE json_extract(json,\'$.createdAt\') < ?').run(Date.now()-15*60*1000);this.db.prepare('INSERT INTO previews VALUES(?,?)').run(p.id,JSON.stringify(p));return p;}
  commit(id,role){const found=this.db.prepare('SELECT json FROM previews WHERE id=?').get(id);must(found,'Preview expired or already imported',409);const p=JSON.parse(found.json);must(role===(p.kind==='payroll'?'hr':'finance'),'Switch to the responsible reviewer role',403);must(Date.now()-p.createdAt<15*60*1000,'Preview expired; upload again',409);
    return this.mutate(p.revision,`Imported ${p.kind}: ${p.filename}`,s=>{s.datasets[p.kind]=p.rows;s.revision++;s.imports.push({id:p.id,kind:p.kind,filename:p.filename,hash:p.hash,sheet:p.sheet,count:p.rows.length,revision:s.revision,at:new Date().toISOString()});this.db.prepare('DELETE FROM previews WHERE id=?').run(id);});}
  evidence(id,filename,mime,body,revision){must(/^[A-Za-z0-9_-]{1,80}$/.test(id),'Evidence ID must use letters, digits, hyphens or underscores');return this.mutate(revision,`Uploaded evidence ${id}`,s=>{must(!s.evidence.some(e=>e.id===id),'Evidence ID exists. Use a new ID and update the source file.');this.db.prepare('INSERT INTO files VALUES(?,?)').run(id,body);s.revision++;s.evidence.push({id,filename,mime,size:body.length,hash:hash(body),at:new Date().toISOString()});});}
  file(id){return this.db.prepare('SELECT body FROM files WHERE id=?').get(id)?.body;}
  saveRun(run){this.db.prepare('INSERT OR REPLACE INTO runs VALUES(?,?)').run(run.id,JSON.stringify(run));}
  runs(){return this.db.prepare('SELECT json FROM runs ORDER BY rowid DESC LIMIT 30').all().map(r=>JSON.parse(r.json));}
  report(run){must(run.status==='completed'&&run.answer,'Only successful AI runs can create drafts');return this.mutate(null,`AI draft ${run.id} saved`,s=>{s.reports.unshift({id:randomUUID(),runId:run.id,revision:run.snapshot.revision,createdAt:new Date().toISOString(),status:'draft',mode:'ai',provider:run.provider,model:run.model,answer:run.answer,trace:run.trace,snapshot:run.snapshot,analysis:analyze(run.snapshot),decisions:[]});});}
  ruleReport(expected){return this.mutate(expected,'Rule report saved for review',s=>{s.reports.unshift({id:randomUUID(),revision:s.revision,createdAt:new Date().toISOString(),status:'draft',mode:'rules',answer:'Deterministic reconciliation report. No AI model was used.',snapshot:{revision:s.revision,datasets:s.datasets,imports:s.imports,evidence:s.evidence},analysis:analyze(s),decisions:[]});});}
  decision({id,action,note,role,revision}){must(typeof note==='string'&&note.trim().length>0&&note.length<=1000,'Review notes are required (up to 1,000 characters)');return this.mutate(revision,`${role} recorded ${action}`,s=>{const r=s.reports.find(r=>r.id===id);must(r,'Report not found',404);must(r.revision===s.revision&&r.analysis.ruleVersion===RULE_VERSION&&r.analysis.payrollRuleVersion===require('../dist/core.js').RULE_VERSION,'This report is historical. Generate a new draft.',409);
    if(action==='review'){must(role==='finance'&&r.status==='draft','Finance must review a draft first',403);must(r.analysis.issues.length===0,'Resolve blocking findings and generate a new draft before review');r.status='reviewed';}
    else if(['approve','reject'].includes(action)){must(role==='director'&&r.status==='reviewed','Director decisions require finance review',403);r.status=action==='approve'?'approved':'rejected';}
    else must(false,'Unknown decision');r.decisions.push({action,note:note.trim(),role,at:new Date().toISOString()});});}
  close(){this.db.close();}
  edit({kind,id,changes,note,revision,role}){const {SCHEMAS,normalize}=require('./imports.cjs');must(SCHEMAS[kind],'Unknown dataset');must(role===(kind==='payroll'?'hr':'finance'),'Switch to the responsible reviewer role',403);must(typeof note==='string'&&note.trim()&&note.length<=1000,'Enter a change explanation');must(changes&&typeof changes==='object'&&!Array.isArray(changes)&&Object.keys(changes).every(k=>SCHEMAS[kind].includes(k)&&k!=='id'),'Invalid edit fields');return this.mutate(revision,`Edited ${kind}:${id}: ${note}`,s=>{const rows=s.datasets[kind],index=rows.findIndex(r=>r.id===id);must(index>=0,'Record not found',404);const before=rows[index],after={...before,...changes,id};const next=rows.map((r,i)=>i===index?after:r);s.datasets[kind]=normalize(kind,[SCHEMAS[kind],...next.map(r=>SCHEMAS[kind].map(k=>r[k]))]);s.revision++;s.events.push({id:randomUUID(),at:new Date().toISOString(),action:'Record change details',source:`${kind}:${id}`,before,after:s.datasets[kind][index],note,revision:s.revision});});}
}
module.exports={Store,must,hash};
